# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build, with maven
on:
  workflow_call:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Delete unwanted jars
        run: |
          rm build/libs/*sources*.jar
          rm build/libs/*-dev*.jar
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest dev build"
          files: |
            build/libs/worldnamepacket*.jar
